name: Build and Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test -- --watchAll=false

      - name: Build React App
        run: npm run build

      - name: Upload production-ready files
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
